export enum CommonTypes {
    ACTION_START = "ACTION_START",
    ACTION_END = "ACTION_END",
    LOGIN_CLEAR_ERROR ='LOGIN_CLEAR_ERROR'
}

export enum LoginTypes {
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILED = "LOGIN_FAILED",
    LOGIN_CLEAR_ERROR = 'LOGIN_CLEAR_ERROR'
}